baseurl             = "https://berquist.github.io/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
theme               = "cocoa"
author              = "Eric Berquist"
title               = "Eric Berquist"
pygmentsuseclasses  = true
disqusShortname     = ""
pluralizelisttitles = false
googleAnalytics     = ""

[permalinks]
blog  = "blog/:slug/"

[[menu.main]]
name                   = "Blog"
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "Pages"
identifier             = "pages"
url                    = "/pages/"

[params]
# include RSS <link> tag in <head> and show RSS icon
include_rss            = true
# how many posts to display on the home page
latestpostscount       = 5
# whether to display small country flags for available translations
i18n_flags             = false
author                 = "Eric Berquist"
# add the current unix timestamp in query string for cache busting css assets
cachebuster            = true
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
# description            = "Don't panic"
# email                  = "you@example.space"
# In your `static` directory, add/remove files as necessary.
extracssfiles          = [ "/css/override.css" ]
faviconfile            = "img/leaf.ico"
github                 = "//github.com/berquist"
lang                   = "en"
# if true, don't show "<x> minutes read" in posts
noshowreadtime         = false
# appears in the site header when set to a non-empty string
selfintro              = ""
twitter                = "//twitter.com/triprotic"
# mastodon               = "//example.com/@you"
keybase                = "//keybase.io/berquist"

highlightjs            = true
# additional languages not included in the "common" set
# highlightjslanguages = ["go"]
# highlightjsStyle     = "darcula"

# path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
# avatar                 = "img/profile.png"
# gravatar hash. see https://en.gravatar.com/site/implement/hash/. do not use in the same time as avatar
gravatar               = "5c4845ced96093ba29d9b3bab42deed7"

[markup.goldmark.renderer]
unsafe = true
